# namespace configs
namespace: llm-servings

# model configs
configs:
  name: ibm-granite
  serve:
    - >
      vllm serve ibm-granite/granite-3.3-8b-instruct
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 1
      --no-enable-prefix-caching
      --trust-remote-code
      --seed 0
      --gpu-memory-utilization 0.95
      --max-model-len 44000

# service id
serviceid: "1"
