---
# Storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vllm-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-local-pv-ibm1
  namespace: llm-servings
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: vllm-local
  persistentVolumeReclaimPolicy: Retain # data is preserved even if the PVC is deleted
  hostPath:
    path: "/mnt/vllm" # path on the node's filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "sunyibm1.fsl.cs.sunysb.edu"
---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-local-pv-ibm2
  namespace: llm-servings
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: vllm-local
  persistentVolumeReclaimPolicy: Retain # data is preserved even if the PVC is deleted
  hostPath:
    path: "/mnt/vllm" # path on the node's filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "sunyibm2.fsl.cs.sunysb.edu"
