apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: llm-servings
  labels:
    app: vllm
spec:
  ports:
  - name: http-vllm
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm
  sessionAffinity: None
  type: ClusterIP
